-- create all dictionary tables and related things
USE JCWAP_DICT;
CREATE TABLE SYS_DICT (
  DICT_ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  DICT_PARENT_ID int(11) NOT NULL DEFAULT 0 COMMENT 'parent id',
  DICT_NATURE varchar(50) NOT NULL COMMENT 'nature',
  DICT_CODE varchar(50) NOT NULL COMMENT 'code',
  DICT_VALUE varchar(50) NOT NULL COMMENT 'display value',
  DICT_PINYIN varchar(100) NOT NULL COMMENT 'pinyin of display value',
  DICT_PINYIN_SHORT varchar(16) NOT NULL COMMENT 'pinyin for short of display value',
  DICT_DESCRIPTION varchar(150) DEFAULT NULL COMMENT 'description',
  DICT_ORDER int(5) NOT NULL COMMENT 'order number',
  IS_ENABLED tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 for enable',
  IS_SYS_DEFINED tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 for system defined',
  PRIMARY KEY (DICT_ID),
  KEY SYS_DICT_DICT_NATURE (DICT_NATURE),
  KEY SYS_DICT_DICT_CODE (DICT_CODE)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COMMENT='Application Dictionary Table';




CREATE TABLE SYS_DICT_AUD
(
    REV_ID INT(11) NOT NULL COMMENT 'REVISION ID',
    REV_TYPE TINYINT(4) DEFAULT NULL COMMENT 'REVTYPE 0:ADD, 1:UPDATE, 2:DELETE',
    DICT_ID INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    DICT_PARENT_ID INT(11) DEFAULT null COMMENT 'parent id',
    DICT_NATURE VARCHAR(50) NOT NULL COMMENT 'nature',
    DICT_CODE VARCHAR(50) NOT NULL COMMENT 'code',
    DICT_VALUE VARCHAR(50) NOT NULL COMMENT 'value',
    IS_ENABLED TINYINT(1) DEFAULT '1' NOT NULL COMMENT '1 for enable',
    PRIMARY KEY (DICT_ID, REV_ID)
) COMMENT = 'Application Dictionary Audit Table';