INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-1, 0, 'ROOT', 'NATURE', '字典管理', 'zidianguanli', 'zdgl', 1);

INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10010001, -1, 'USER_TYPE', 'NATURE', '用户类型', 'yonghuleixing', 'yhlx', 1);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10010002, -10010001, 'USER_TYPE', 'ADMIN', '超级用户', 'chaojiyonghu', 'cjyh', 1);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10010003, -10010001, 'USER_TYPE', 'NORMAL', '普通用户', 'putongyonghu', 'ptyh', 2);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10010004, -10010001, 'USER_TYPE', 'ANONYMOUS', '匿名用户', 'nimingyonghu', 'nmyh', 3);

INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10020001, -1, 'SEX', 'NATURE', '性别', 'xingbie', 'xb', 2);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10020002, -10020001, 'SEX', '0', '男', 'nan', 'n', 1);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10020003, -10020001, 'SEX', '1', '女', 'nv', 'n', 2);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10020004, -10020001, 'SEX', '2', '未知', 'weizhi', 'wz', 3);

INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10030001, -1, 'MENU_TYPE', 'NATURE', '菜单类型', 'caidanleixing', 'cdlx', 3);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10030002, -10030001, 'MENU_TYPE', 'LINK', '链接', 'lianjie', 'lj', 1);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10030003, -10030001, 'MENU_TYPE', 'MENU', '菜单', 'caidan', 'cd', 2);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10030004, -10030001, 'MENU_TYPE', 'FEATURE', '模块', 'mokuai', 'mk', 3);

INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10040001, -1, 'YESNO', 'NATURE', '是否', 'shifou', 'sf', 4);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10040002, -10040001, 'YESNO', '0', '否', 'fou', 'f', 1);
INSERT INTO SYS_DICT (DICT_ID, DICT_PARENT_ID, DICT_NATURE, DICT_CODE, DICT_VALUE, DICT_PINYIN, DICT_PINYIN_SHORT, DICT_ORDER)
VALUES (-10040003, -10040001, 'YESNO', '1', '是', 'shi', 's', 2);