/**
 * Project Name : jcwap-dict-api <br>
 * File Name : DictService.java <br>
 * Package Name : com.lee.jcwap.dict.service <br>
 * Create Time : 2016-09-23 <br>
 * Create by : jimmyblylee@126.com <br>
 * Copyright © 2006, 2016, Jimmybly Lee. All rights reserved.
 */
package com.lee.jcwap.dict.service;

import java.util.List;

import com.lee.jcwap.dict.entity.SysDict;
import com.lee.jwaf.exception.ServiceException;

/**
 * ClassName : DictService <br>
 * Description : Operation service of SysDict <br>
 * Create Time : 2016-09-23 <br>
 * Create by : jimmyblylee@126.com
 */
public interface DictService {

    /**************************
     * for JEE support
     **************************/
    public final static String NAME = "dict-service/DictService";
    public final static String JNDI = NAME + "/remote";

    public static interface Remote extends DictService {};

    public static interface Local extends DictService {};

    /**************************
     * simple operation for CREATE REMOVE UPDATE
     *************************/
    /**
     * Description : create SysDict by given dict <br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dict the dict entity
     * @return the entity created with filling infos: id, pinyin, enabled(true as default)
     * @throws ServiceException dict is null, or validation failed
     */
    public SysDict createDictionary(SysDict dict) throws ServiceException;

    /**
     * Description : create SysDict by given list<br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dictList the list of dict
     * @throws ServiceException dictList is null or there are some entity can not pass the validation
     */
    public void createDictionary(List<SysDict> dictList) throws ServiceException;

    /**
     * Description : remove SysDict by given id <br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dictId the dictId
     * @throws ServiceException given id is null or could not find SysDict by given id
     */
    public void removeDictionariesById(Integer dictId) throws ServiceException;

    /**
     * Description : remove SysDict by given ids <br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dictIds the dictId
     * @throws ServiceException given id is null or could not find SysDict by given id
     */
    public void removeDictionariesById(List<Integer> dictIds) throws ServiceException;

    /**
     * Description : remove SysDict by given nature <br>
     * Create Time: Apr 14, 2016 <br>
     * Create by : xiangyu_li@asdc.com.cn <br>
     *
     * @param nature dict nature
     * @return count of removed dicts
     * @throws ServiceException nature is null
     */
    public int removeDictionaryByNature(String nature) throws ServiceException;

    /**
     * Description : udpate SysDict by given dict<br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dict the dict
     * @return the updated SysDict with new pinyin generated by given value of SysDict
     * @throws ServiceException dict is null or entity validation failed
     */
    public SysDict updateDictionary(SysDict dict) throws ServiceException;

    /**
     * Description : udpate SysDict by given dicts <br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param dicts the dict
     * @return the updated SysDict with new pinyin generated by given value of SysDict
     * @throws ServiceException dict is null or entity validation failed
     */
    public SysDict updateDictionary(List<SysDict> dicts) throws ServiceException;

    /**************************
     * query
     *************************/
    /**
     * Description : get the SysDict by given nature string and code string <br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param nature dict nature
     * @param code dict code
     * @return the entity of SysDict with given nature and code
     * @throws ServiceException if nature or code is null
     */
    public SysDict getDictByNatureAndCode(String nature, String code) throws ServiceException;

    /**
     * Description : query SysDict by condition which is an instance of SysDIct, and fileds with value will be a condition will search by "like" <br>
     * for parent and children search condition, only support parent "nature" condition<br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param condition SysDict condition
     * @return list of SysDict
     * @throws ServiceException condition is null
     */
    public List<SysDict> querySysDict(SysDict condition) throws ServiceException;

    /**
     * Description : query SysDict by condition which is an instance of SysDIct, and fileds with value will be a condition will search by "like" <br>
     * for parent and children search condition, only support parent "nature" condition<br>
     * Create Time: 2016-09-23 <br>
     * Create by : jimmyblylee@126.com <br>
     *
     * @param condition SysDict condition
     * @param start page start
     * @param limit -1 for skipping page limit, and return all the SysDict
     * @return count of result
     * @throws ServiceException condition is null
     */
    public Integer getCount(SysDict condition, int start, int limit) throws ServiceException;

}
